### ISSUE TITLE
坐标系

### ISSUE THREAD

**Issue by Zyxiiiii** [YmSakura/Reality#1]
总体来说很不错，在短时间内掌握了git的使用，并且明白什么是**细粒度**上传，下面是我的一点点小建议：
- 上传格式的开头那个说明不用尖括号，不过影响不大
- 分包还有所欠缺，不同类型的脚本之间应该分成不同的包，如控制人物的，控制敌人的，处理逻辑的等等
- 上传的内容有些冗杂，不是所有东西都需要上传上来的，可以自己了解一下有什么是需要上传的有什么是不需要上传的

**Comment by YmSakura** [comment]
感谢建议，分包后面会修改，然后冗杂是指shaderlab那些的吗，那个是导入的字体资源包里面的，我觉得应该要上传的吧

**Comment by Zyxiiiii** [comment]
问题不大，我当时可能没仔细看，我以为你没用`.gitignore`，就这样就好，所有的素材都是需要上传的:smile:

**Comment by YmSakura** [comment]
好的好的
